result
=
SELECT user_id,
       sku_id,
       sku_name,
       tm_id,
       tm_name,
       category1_id,
       category1_name,
       category2_id,
       category2_name,
       category3_id,
       category3_name,
       sum(if(date_id >= date_sub("${date}", 0), order_count_1d, 0))            order_count_1d,
       sum(if(date_id >= date_sub("${date}", 0), order_num_1d, 0))              order_num_1d,
       sum(if(date_id >= date_sub("${date}", 0), order_original_amount_1d, 0))  order_original_amount_1d,
       sum(if(date_id >= date_sub("${date}", 0), activity_reduce_amount_1d, 0)) activity_reduce_amount_1d,
       sum(if(date_id >= date_sub("${date}", 0), coupon_reduce_amount_1d, 0))   coupon_reduce_amount_1d,
       sum(if(date_id >= date_sub("${date}", 0), order_total_amount_1d, 0))     order_total_amount_1d,
       sum(if(date_id >= date_sub("${date}", 6), order_count_1d, 0))            order_count_7d,
       sum(if(date_id >= date_sub("${date}", 6), order_num_1d, 0))              order_num_7d,
       sum(if(date_id >= date_sub("${date}", 6), order_original_amount_1d, 0))  order_original_amount_7d,
       sum(if(date_id >= date_sub("${date}", 6), activity_reduce_amount_1d, 0)) activity_reduce_amount_7d,
       sum(if(date_id >= date_sub("${date}", 6), coupon_reduce_amount_1d, 0))   coupon_reduce_amount_7d,
       sum(if(date_id >= date_sub("${date}", 6), order_total_amount_1d, 0))     order_total_amount_7d,
       sum(order_count_1d)                                                      order_count_30d,
       sum(order_num_1d)                                                        order_num_30d,
       sum(order_original_amount_1d)                                            order_original_amount_30d,
       sum(activity_reduce_amount_1d)                                           activity_reduce_amount_30d,
       sum(coupon_reduce_amount_1d)                                             coupon_reduce_amount_30d,
       sum(order_total_amount_1d)                                               order_total_amount_30d
FROM trade_user_sku_order_1d
GROUP BY user_id,
         sku_id,
         sku_name,
         tm_id,
         tm_name,
         category1_id,
         category1_name,
         category2_id,
         category2_name,
         category3_id,
         category3_name